export enum MessageType {
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  INJECT_NAV_SCRIPT = "INJECT_NAV_SCRIPT",
  GET_STORAGE = "GET_STORAGE",
  SET_STORAGE = "SET_STORAGE",
  SCRAPE_PROFILE = "SCRAPE_PROFILE",
}
